#pragma once


//	THE PURPOSE OF THIS CLASS IS TO EXPOSE THE CORE SYSTEMS OF THE ENGINE WITHOUT NEEDING TO INCLUDE THEM AND PASS REFERENCES.
//  THIS APROACH REQUIRES SYSTEMS.H TO BE INCLUDED AS WELL AS ANY OF THE DESIRED SYSTEMS THAT NEED TO BE USED
class Renderer;
class InputManager;
static struct ENGINE_SYSTEMS
{
	static void* RENDERER_CLASS;
	static void* INPUT_CLASS;

	static Renderer* GET_RENDERER();
	static InputManager* GET_INPUTMANAGER();
};